# -*- coding: utf-8 -*-
"""MethodsX Paper - Response Elicitation Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gE7h6Y4Kt795vgMR8UuewK7FGVC4bcZk

# About

This code was authored by Kevin Corti in May 2026. It reflects the Python workflow with the OpenAI Responses API that was used to fetch demonstration data for the MethodsX article: "Building factorial prompt matrices using query targets and configurable factor classes: A methods framework for conversational AI response behavior research".

Code was produced and executed using Google Colab.

Requirements: To run this code end-to-end, one must supply an OpenAI API key.

API use costs: At the time the final version of this code was produced to fetch all the demonstration data used in the above article, the total OpenAI costs were ~ $11.75 USD.

Expected runtime: At the time the final version of this code was produced to fetch demonstration data, the codeblocks for the demonstrations took < 1 hr. each, with the exception of demonstration 5, which took approx 3-4 hrs.

Tool disclosures: The author discloses that portions of this code were produced with the assistance of Google Gemini code assist (via Google Colab), especially for de-bugging, consistency, formatting, and readability purposes. The OpenAI API codeblocks were developed using ChatGPT's code assist features, as they proved more robust and are native to OpenAI.

Contact: research@jebeldata.com

# Initialize

## Load and import OpenAI and other libraries
"""

# Install the OpenAI library.
!pip install openai -q

# Import needed libraries

import openai
import datetime
import json
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
from io import StringIO

"""## Initialize OpenAI"""

# Insert OpenAI API Key inside the quotation marks:
OPENAI_API_KEY = ""

# Authenticate with OpenAI using the API key established above.
client = openai.OpenAI(api_key=OPENAI_API_KEY)

"""# Create dataframes from which Factorial Prompt Matrices will be developed

In this group of code blocks, we are going to create separate dataframes for the sampling spine as well as the different groups of factors by factor family.

These will be invoked in the individual demos to build factorial prompt matrices (FPMs).

In practice, there are many ways to build FPMs from data objects containing the relevant factor levels, categorizations, and associations. The protocol followed here is more illustrative than prescriptive.

## Create dataframe for spine from ICD-11 Mycoses conditions
"""

# This code defines a df consisting of the of 60 individual
# Mycoses conditions from the ICD-11 (https://icd.who.int/browse/2026-01/mms/en)
# and their classification metadata.
# Citation: World Health Organization. ICD-11: International Classification of Diseases,
#   Eleventh Revision [Internet]. Geneva: World Health Organization; 2019.
#   https://icd.who.int/browse11.

Icd_Raw = """FoundationUri	LinearizationUri	Code	Blockname	Title
http://id.who.int/icd/entity/710893141	http://id.who.int/icd/release/11/mms/710893141	1F20.00	Mycoses	Invasive aspergillosis of the digestive tract
http://id.who.int/icd/entity/2019158769	http://id.who.int/icd/release/11/mms/2019158769	1F20.01	Mycoses	Invasive cerebral aspergillosis
http://id.who.int/icd/entity/489221449	http://id.who.int/icd/release/11/mms/489221449	1F20.02	Mycoses	Disseminated aspergillosis
http://id.who.int/icd/entity/942630604	http://id.who.int/icd/release/11/mms/942630604	1F20.10	Mycoses	Aspergillus otomycosis
http://id.who.int/icd/entity/1355660816	http://id.who.int/icd/release/11/mms/1355660816	1F20.11	Mycoses	Chronic aspergillosis of the paranasal sinuses
http://id.who.int/icd/entity/86747759	http://id.who.int/icd/release/11/mms/86747759	1F20.12	Mycoses	Chronic pulmonary aspergillosis
http://id.who.int/icd/entity/2132861880	http://id.who.int/icd/release/11/mms/2132861880	1F20.13	Mycoses	Tonsillar aspergillosis
http://id.who.int/icd/entity/107634429	http://id.who.int/icd/release/11/mms/107634429	1F20.14	Mycoses	Aspergillus bronchitis
http://id.who.int/icd/entity/1478604320	http://id.who.int/icd/release/11/mms/1478604320	1F20.15	Mycoses	Obstructing aspergillus tracheobronchitis
http://id.who.int/icd/entity/2087283296	http://id.who.int/icd/release/11/mms/2087283296	1F21	Mycoses	Basidiobolomycosis
http://id.who.int/icd/entity/1968108845	http://id.who.int/icd/release/11/mms/1968108845	1F22	Mycoses	Blastomycosis
http://id.who.int/icd/entity/520566646	http://id.who.int/icd/release/11/mms/520566646	1F23.0	Mycoses	Candidosis of lips or oral mucous membranes
http://id.who.int/icd/entity/1806329739	http://id.who.int/icd/release/11/mms/1806329739	1F23.10	Mycoses	Vulvovaginal candidosis
http://id.who.int/icd/entity/407172127	http://id.who.int/icd/release/11/mms/407172127	1F23.11	Mycoses	Candida balanoposthitis
http://id.who.int/icd/entity/357498950	http://id.who.int/icd/release/11/mms/357498950	1F23.12	Mycoses	Flexural or intertriginous candidosis
http://id.who.int/icd/entity/828693449	http://id.who.int/icd/release/11/mms/828693449	1F23.13	Mycoses	Candidosis of nail or paronychium
http://id.who.int/icd/entity/2120780687	http://id.who.int/icd/release/11/mms/2120780687	1F23.14	Mycoses	Chronic mucocutaneous candidosis
http://id.who.int/icd/entity/92452740	http://id.who.int/icd/release/11/mms/92452740	1F23.15	Mycoses	Disseminated cutaneous candidosis
http://id.who.int/icd/entity/1064943355	http://id.who.int/icd/release/11/mms/1064943355	1F23.16	Mycoses	Candida otomycosis
http://id.who.int/icd/entity/1229869827	http://id.who.int/icd/release/11/mms/1229869827	1F23.2	Mycoses	Candidosis of gastrointestinal tract
http://id.who.int/icd/entity/2098149771	http://id.who.int/icd/release/11/mms/2098149771	1F23.30	Mycoses	Candida meningitis
http://id.who.int/icd/entity/2051865312	http://id.who.int/icd/release/11/mms/2051865312	1F23.31	Mycoses	Pulmonary candidosis
http://id.who.int/icd/entity/1438584733	http://id.who.int/icd/release/11/mms/1438584733	1F24	Mycoses	Chromoblastomycosis
http://id.who.int/icd/entity/1367598280	http://id.who.int/icd/release/11/mms/1367598280	1F25.00	Mycoses	Acute pulmonary coccidioidomycosis
http://id.who.int/icd/entity/885533022	http://id.who.int/icd/release/11/mms/885533022	1F25.01	Mycoses	Chronic pulmonary coccidioidomycosis
http://id.who.int/icd/entity/577599324	http://id.who.int/icd/release/11/mms/577599324	1F25.10	Mycoses	Disseminated coccidioidomycosis
http://id.who.int/icd/entity/623817783	http://id.who.int/icd/release/11/mms/623817783	1F25.11	Mycoses	Primary cutaneous coccidioidomycosis
http://id.who.int/icd/entity/1455433635	http://id.who.int/icd/release/11/mms/1455433635	1F25.12	Mycoses	Coccidioides meningitis
http://id.who.int/icd/entity/1326582778	http://id.who.int/icd/release/11/mms/1326582778	1F26	Mycoses	Conidiobolomycosis
http://id.who.int/icd/entity/1916712542	http://id.who.int/icd/release/11/mms/1916712542	1F27.0	Mycoses	Pulmonary cryptococcosis
http://id.who.int/icd/entity/30418378	http://id.who.int/icd/release/11/mms/30418378	1F27.2	Mycoses	Disseminated cryptococcosis
http://id.who.int/icd/entity/1380450203	http://id.who.int/icd/release/11/mms/1380450203	1F28.0	Mycoses	Dermatophytosis of scalp
http://id.who.int/icd/entity/1731433055	http://id.who.int/icd/release/11/mms/1731433055	1F28.1	Mycoses	Dermatophytosis of nail
http://id.who.int/icd/entity/1993674550	http://id.who.int/icd/release/11/mms/1993674550	1F28.2	Mycoses	Dermatophytosis of foot
http://id.who.int/icd/entity/350028235	http://id.who.int/icd/release/11/mms/350028235	1F28.3	Mycoses	Genitocrural dermatophytosis
http://id.who.int/icd/entity/1449494917	http://id.who.int/icd/release/11/mms/1449494917	1F28.4	Mycoses	Kerion
http://id.who.int/icd/entity/2003167397	http://id.who.int/icd/release/11/mms/2003167397	1F28.5	Mycoses	Disseminated dermatophytosis
http://id.who.int/icd/entity/1866587875	http://id.who.int/icd/release/11/mms/1866587875	1F29	Mycoses	Eumycetoma
http://id.who.int/icd/entity/1553838370	http://id.who.int/icd/release/11/mms/1553838370	1F2A.0	Mycoses	Pulmonary histoplasmosis capsulati
http://id.who.int/icd/entity/997943937	http://id.who.int/icd/release/11/mms/997943937	1F2A.1	Mycoses	Histoplasmosis due to Histoplasma duboisii
http://id.who.int/icd/entity/566562143	http://id.who.int/icd/release/11/mms/566562143	1F2B	Mycoses	Lobomycosis
http://id.who.int/icd/entity/1676389165	http://id.who.int/icd/release/11/mms/1676389165	1F2C	Mycoses	Mucormycosis
http://id.who.int/icd/entity/67108853	http://id.who.int/icd/release/11/mms/67108853	1F2D.0	Mycoses	Pityriasis versicolor
http://id.who.int/icd/entity/12958750	http://id.who.int/icd/release/11/mms/12958750	1F2D.1	Mycoses	Malassezia folliculitis
http://id.who.int/icd/entity/303653536	http://id.who.int/icd/release/11/mms/303653536	1F2D.2	Mycoses	White piedra
http://id.who.int/icd/entity/1990974193	http://id.who.int/icd/release/11/mms/1990974193	1F2D.3	Mycoses	Black piedra
http://id.who.int/icd/entity/1723085409	http://id.who.int/icd/release/11/mms/1723085409	1F2D.4	Mycoses	Tinea nigra
http://id.who.int/icd/entity/1414602212	http://id.who.int/icd/release/11/mms/1414602212	1F2D.5	Mycoses	Onychomycosis due to non-dermatophyte mould
http://id.who.int/icd/entity/1220568868	http://id.who.int/icd/release/11/mms/1220568868	1F2E.0	Mycoses	Pulmonary paracoccidioidomycosis
http://id.who.int/icd/entity/992933048	http://id.who.int/icd/release/11/mms/992933048	1F2E.1	Mycoses	Disseminated paracoccidioidomycosis
http://id.who.int/icd/entity/547567937	http://id.who.int/icd/release/11/mms/547567937	1F2F	Mycoses	Phaeohyphomycosis
http://id.who.int/icd/entity/2014927218	http://id.who.int/icd/release/11/mms/2014927218	1F2G.0	Mycoses	Pulmonary pneumocystosis
http://id.who.int/icd/entity/807637046	http://id.who.int/icd/release/11/mms/807637046	1F2H	Mycoses	Scedosporiosis
http://id.who.int/icd/entity/768312788	http://id.who.int/icd/release/11/mms/768312788	1F2J.0	Mycoses	Lymphocutaneous sporotrichosis
http://id.who.int/icd/entity/1370512518	http://id.who.int/icd/release/11/mms/1370512518	1F2J.1	Mycoses	Fixed cutaneous sporotrichosis
http://id.who.int/icd/entity/1229440796	http://id.who.int/icd/release/11/mms/1229440796	1F2J.2	Mycoses	Pulmonary sporotrichosis
http://id.who.int/icd/entity/984175752	http://id.who.int/icd/release/11/mms/984175752	1F2J.3	Mycoses	Disseminated sporotrichosis
http://id.who.int/icd/entity/646368820	http://id.who.int/icd/release/11/mms/646368820	1F2K	Mycoses	Talaromycosis
http://id.who.int/icd/entity/210760879	http://id.who.int/icd/release/11/mms/210760879	1F2L.0	Mycoses	Disseminated adiaspiromycosis
http://id.who.int/icd/entity/1111587867	http://id.who.int/icd/release/11/mms/1111587867	1F2L.1	Mycoses	Pulmonary adiaspiromycosis"""

# Parse the raw string directly into a DataFrame using StringIO.
# sep="\t" tells pandas the columns are tab-delimited.
IcdConditions = pd.read_csv(StringIO(Icd_Raw), sep="\t")

# Check that the result is 5 columns and 60 rows:
print(IcdConditions.shape)
print(IcdConditions.head())

"""## Create individual factor-level dataframes for building future FPMs

### LLM Factor Class
"""

# Create a shell dataframe to store the LLMs:
LLMs = pd.DataFrame(columns=['ModelNameWithAlias', 'ModelName'])

# Define a list of ChatGPT model names to be used in the demos.
# Note, aliases are added to indicate latest releases as of May 2026 and are
# included for replication purposes:
GptModelNameWithAlias = ["gpt-5-nano-2025-08-07", "gpt-5.4-nano-2026-03-17", "gpt-5.4-mini-2026-03-17"]
GptModelName = ["gpt-5-nano", "gpt-5.4-nano", "gpt-5.4-mini"]

# Populate LLMs dataframe accordingly:
LLMs['ModelNameWithAlias'] = GptModelNameWithAlias
LLMs['ModelName'] = GptModelName

# Sanity check:
print(LLMs)

"""### Product-System and User Context Factor Classes"""

# Create a dataframe to store Reasoning  to be used in certain demos:

ReasoningLevel = pd.DataFrame(columns=['ReasoningLevel'])

ReasoningLevels = [
    "none",
    "low"
    ]

# Populate:
ReasoningLevel['ReasoningLevel'] = ReasoningLevels

# Sanity check:
print(ReasoningLevel)

# Create a dataframe to store System Instruction to be used in certain demos:

ProductSystem_SystemInstructions = pd.DataFrame(columns=['SystemContent', 'SystemContentLevelLabels'])

SystemContent = [
    "",
    "Consider using web search to ground your answer."    ]

SystemContentLevelLabels = [
    "None",
    "Directive: web search nudge"    ]


# Populate:
ProductSystem_SystemInstructions['SystemContent'] = SystemContent
ProductSystem_SystemInstructions['SystemContentLevelLabels'] = SystemContentLevelLabels

# Sanity check:
print(ProductSystem_SystemInstructions)

# Same as above, but for Developer instructions:

ProductSystem_DeveloperInstructions = pd.DataFrame(columns=['DeveloperContent', 'DeveloperContentLevelLabels'])

DeveloperContent = [
    "",
    "Consider using web search to ground your answer.",
    "Known user persona: user often conducts literature reviews for scientific papers"
    ]

DeveloperContentLevelLabels = [
    "None",
    "Directive: web search nudge",
    "Persona: biomedical researcher"
    ]

# Populate:
ProductSystem_DeveloperInstructions['DeveloperContent'] = DeveloperContent
ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] = DeveloperContentLevelLabels

# Sanity check:
print(ProductSystem_DeveloperInstructions)

"""### Query Design Factor Class"""

# Create a dataframe to store Phrase Templates that are used to build queries:
QueryDesign_QueryPhraseTemplate = pd.DataFrame(columns=['QueryPhraseContent', 'QueryPhraseContentLevelLabels'])

QueryPhraseContent = [
    "%X%",
    "What is %X%?",
    "What are risk factors for %X%?",
    "What is the standard of care treatment protocol for %X%?"
    ]

QueryPhraseContentLevelLabels = [
    "Blank",
    "General description",
    "Risk factors",
    "Standard of care treatment"
    ]

# Populate:
QueryDesign_QueryPhraseTemplate['QueryPhraseContent'] = QueryPhraseContent
QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] = QueryPhraseContentLevelLabels

# Sanity check:
print(QueryDesign_QueryPhraseTemplate)

# Create a dataframe to store phrase suffixes used in certain demos:
QueryDesign_Suffixes = pd.DataFrame(columns=['SuffixPhrases', 'SuffixPhraseLevelLabels'])

SuffixPhrases = [
    "",
    "Consider using web search to ground your answer."
    ]

SuffixPhraseLevelLabels = [
    "None",
    "Directive: web search nudge"
    ]

# Populate:
QueryDesign_Suffixes['SuffixPhrases'] = SuffixPhrases
QueryDesign_Suffixes['SuffixPhraseLevelLabels'] = SuffixPhraseLevelLabels

# Sanity check:
print(QueryDesign_Suffixes)

"""# Define a function to fetch responses from OpenAI in a standardized manner

In this section, we are going to create a function, to be used in all demos,
that takes a pre-response FPM and passes it row-by-row to the Responses API.
"""

def process_openai_queries(df_input):

    # make a copy of the dataframe passed to the function so as not to alter
    # the original:
    df = df_input.copy()

    # Initialize result columns; set default values:
    df["ModelResponseText"] = None
    df["WebSearchUsed"] = False
    df["ResponseCompletionTimestamp"] = None
    df["UniqueUrlCount"] = 0
    df["DedupedUrls"] = ""

    for row_index, request_row in tqdm(
        df.iterrows(),
        total=len(df),
        desc="Calling OpenAI API"
    ):

        # Pull row-level inputs for this API call.
        model_name = request_row["ModelNameWithAlias"]
        generated_query = request_row["GeneratedQueryContent"]

        # The Responses API request with the system, developer, and user
        # content supplied as distinct roles, as per API documentation protocols:

        api_call_args = {
            "model": model_name,
            "max_output_tokens": 10000, # Arbitrarily large for demo purposes.
            "tools": [
                {"type": "web_search"}
            ],
            "input": [
                {
                    "role": "system",
                    "content": request_row["SystemContent"]
                },
                {
                    "role": "developer",
                    "content": request_row["DeveloperContent"]
                },
                {
                    "role": "user",
                    "content": generated_query
                }
            ]
        }

        # Optionally pass through a reasoning factor if contained in FPM.
        # Not every FPM includes this column, so check for it first.
        if (
            "ReasoningLevel" in df.columns
            and pd.notna(request_row["ReasoningLevel"])
        ):
            api_call_args["reasoning"] = {
                "effort": request_row["ReasoningLevel"]
            }

        # Submit payload:
        response = client.responses.create(**api_call_args)

        # Extract final plain-text response:
        model_response_text = response.output_text

        # Distinguish actual web search use from web search merely being enabled:
        web_search_used = any(
            getattr(output_item, "type", None) == "web_search_call"
            for output_item in response.output
        )

        # Extract cited URLs from any response annotations that are present:
        unique_urls = set()

        for output_item in response.output:
            for content_item in (getattr(output_item, "content", None) or []):
                for annotation in (getattr(content_item, "annotations", None) or []):
                    url = getattr(annotation, "url", None)
                    if url:
                        unique_urls.add(url)

        # Store URLs as a stable JSON string:
        deduped_urls = json.dumps(sorted(unique_urls))
        unique_url_count = len(unique_urls)

        # Timestamp to record completion of this row's API call:
        response_timestamp = datetime.datetime.now().isoformat()

        # Write outputs back to the FPM:
        df.loc[row_index, "ModelResponseText"] = model_response_text
        df.loc[row_index, "WebSearchUsed"] = web_search_used
        df.loc[row_index, "ResponseCompletionTimestamp"] = response_timestamp
        df.loc[row_index, "UniqueUrlCount"] = unique_url_count
        df.loc[row_index, "DedupedUrls"] = deduped_urls

    return df

"""# Demo 1: Web search invocation across three LLMs

## Create factorial prompt matrix
"""

# Filter the necessary DataFrames based desired conditions for demo 1:
filtered_system_instructions = ProductSystem_SystemInstructions[
    ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "None"
]
filtered_developer_instructions = ProductSystem_DeveloperInstructions[
    ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "None"
]
filtered_phrase_template = QueryDesign_QueryPhraseTemplate[
    QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] == "General description"
]

# To create a Cartesian product, add a dummy key column to all DataFrames
IcdConditions_temp = IcdConditions.copy()
IcdConditions_temp['key'] = 1

LLMs_temp = LLMs.copy()
LLMs_temp['key'] = 1

filtered_system_instructions_temp = filtered_system_instructions.copy()
filtered_system_instructions_temp['key'] = 1

filtered_developer_instructions_temp = filtered_developer_instructions.copy()
filtered_developer_instructions_temp['key'] = 1

filtered_phrase_template_temp = filtered_phrase_template.copy()
filtered_phrase_template_temp['key'] = 1

# Perform merges starting with IcdConditions as the spine:
FPM_1 = pd.merge(IcdConditions_temp, LLMs_temp, on='key')
FPM_1 = pd.merge(FPM_1, filtered_system_instructions_temp, on='key')
FPM_1 = pd.merge(FPM_1, filtered_developer_instructions_temp, on='key')
FPM_1 = pd.merge(FPM_1, filtered_phrase_template_temp, on='key')

# Drop the dummy key column from the result
FPM_1 = FPM_1.drop('key', axis=1)

# Sanity check:
print("Head of FPM_1 DataFrame:")
print(FPM_1.head())
print(f"Shape of FPM_1: {FPM_1.shape}")

# Create a summary table to further sanity check:
summary_table = FPM_1.groupby([
    'ModelName',
    'QueryPhraseContentLevelLabels',
    'DeveloperContentLevelLabels',
    'SystemContentLevelLabels'
]).size().reset_index(name='RecordCount')

print("\nSummary table of record counts:")
print(summary_table)

# Render final generated query by replacing %X% in QueryPhraseContent
# with spine target ("Title" of ICD condition):

FPM_1['GeneratedQueryContent'] = FPM_1.apply(
    lambda row: row['QueryPhraseContent'].replace('%X%', row['Title']), axis=1
)

# Sanity check:
print("Head of FPM_1 DataFrame with new 'GeneratedQueryContent' column:")
print(FPM_1[['Title', 'QueryPhraseContent', 'GeneratedQueryContent']].head())

"""## Run API fetcher to produce data"""

df = process_openai_queries(FPM_1)

# When finished:
FPM_1_Responses = df

# Save to CSV file:
FPM_1_Responses.to_csv('FPM_1_Responses.csv', index=False)

"""# Demo 2: Web search invocation as a function of supplied directive location

## Create factorial prompt matrix
"""

# Filter the necessary DataFrames based on desired conditions for demo 2:
filtered_LLMs = LLMs[
    LLMs['ModelName'] == "gpt-5.4-nano"
]

filtered_system_instructions = ProductSystem_SystemInstructions[
    (ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "Directive: web search nudge") |
    (ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "None")
]

filtered_developer_instructions = ProductSystem_DeveloperInstructions[
    (ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "Directive: web search nudge") |
    (ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "None")
]

filtered_phrase_suffix_template = QueryDesign_Suffixes[
    (QueryDesign_Suffixes['SuffixPhraseLevelLabels'] == "Directive: web search nudge") |
    (QueryDesign_Suffixes['SuffixPhraseLevelLabels'] == "None")
]

filtered_phrase_template = QueryDesign_QueryPhraseTemplate[
    QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] == "General description"
]


# To create a Cartesian product, add a dummy key column to all DataFrames
IcdConditions_temp = IcdConditions.copy()
IcdConditions_temp['key'] = 1

filtered_LLMs_temp = filtered_LLMs.copy()
filtered_LLMs_temp['key'] = 1

filtered_system_instructions_temp = filtered_system_instructions.copy()
filtered_system_instructions_temp['key'] = 1

filtered_developer_instructions_temp = filtered_developer_instructions.copy()
filtered_developer_instructions_temp['key'] = 1

filtered_phrase_suffix_template_temp = filtered_phrase_suffix_template.copy()
filtered_phrase_suffix_template_temp['key'] = 1

filtered_phrase_template_temp = filtered_phrase_template.copy()
filtered_phrase_template_temp['key'] = 1

# Perform merges starting with IcdConditions as the spine
FPM_2 = pd.merge(IcdConditions_temp, filtered_LLMs_temp, on='key')
FPM_2 = pd.merge(FPM_2, filtered_system_instructions_temp, on='key')
FPM_2 = pd.merge(FPM_2, filtered_developer_instructions_temp, on='key')
FPM_2 = pd.merge(FPM_2, filtered_phrase_suffix_template_temp, on='key')
FPM_2 = pd.merge(FPM_2, filtered_phrase_template_temp, on='key')

# Drop the dummy key column from the result
FPM_2 = FPM_2.drop('key', axis=1)

# Sanity Check:
print("Head of FPM_2 DataFrame:")
print(FPM_2.head())
print(f"Shape of FPM_2: {FPM_2.shape}")

# Since this demo is not a full factorial design, we need to specify factor
# level combinations we actually desire to keep and drop the rest:
condition1 = (
    (FPM_2['SystemContentLevelLabels'] == 'None') &
    (FPM_2['DeveloperContentLevelLabels'] == 'None') &
    (FPM_2['SuffixPhraseLevelLabels'] == 'None')
)

condition2 = (
    (FPM_2['SystemContentLevelLabels'] == 'None') &
    (FPM_2['DeveloperContentLevelLabels'] == 'None') &
    (FPM_2['SuffixPhraseLevelLabels'] == 'Directive: web search nudge')
)

condition3 = (
    (FPM_2['SystemContentLevelLabels'] == 'None') &
    (FPM_2['DeveloperContentLevelLabels'] == 'Directive: web search nudge') &
    (FPM_2['SuffixPhraseLevelLabels'] == 'None')
)

condition4 = (
    (FPM_2['SystemContentLevelLabels'] == 'Directive: web search nudge') &
    (FPM_2['DeveloperContentLevelLabels'] == 'None') &
    (FPM_2['SuffixPhraseLevelLabels'] == 'None')
)

# Combine the conditions:
combined_condition = condition1 | condition2 | condition3 | condition4

# Apply the filter to FPM_2
FPM_2 = FPM_2[combined_condition]

# Sanity checks:
print("Head of filtered FPM_2 DataFrame:")
print(FPM_2.head())
print(f"Shape of filtered FPM_2: {FPM_2.shape}")

summary_table_filtered = FPM_2.groupby([
    'ModelName',
    'QueryPhraseContentLevelLabels',
    'DeveloperContentLevelLabels',
    'SystemContentLevelLabels',
    'SuffixPhraseLevelLabels'
]).size().reset_index(name='RecordCount')

print("\nSummary table of record counts:")
print(summary_table_filtered)

# Render final generated query, as in demo 1, but also adding suffixes where
# relevant:
FPM_2['GeneratedQueryContent'] = FPM_2.apply(
    lambda row: (
        row['QueryPhraseContent'].replace('%X%', row['Title']) +
        (" " + row['SuffixPhrases'] if row['SuffixPhrases'] else "")
    ).strip(),
    axis=1
)

print("Head of FPM_2 DataFrame with new 'GeneratedQueryContent' column:")
print(FPM_2[['Title', 'QueryPhraseContent', 'SuffixPhrases', 'GeneratedQueryContent']].head())

"""## Run API fetcher to produce data"""

df = process_openai_queries(FPM_2)

# When finished:
FPM_2_Responses = df

# Save to csv:
FPM_2_Responses.to_csv('FPM_2_Responses.csv', index=False)

"""# Demo 3:  Web search invocation as a function of the LLM and reasoning effort

## Create factorial prompt matrix
"""

# Filter the necessary DataFrames based on the factors we want:
filtered_system_instructions = ProductSystem_SystemInstructions[
    ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "None"
]
filtered_developer_instructions = ProductSystem_DeveloperInstructions[
    ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "None"
]
filtered_phrase_template = QueryDesign_QueryPhraseTemplate[
    QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] == "General description"
]

# Filter LLMs to exclude 'gpt-5-nano' (as only the other LLMs will be used):
filtered_LLMs = LLMs[LLMs['ModelName'] != "gpt-5-nano"].copy()

# To create a Cartesian product, add a dummy key column to all DataFrames
IcdConditions_temp = IcdConditions.copy()
IcdConditions_temp['key'] = 1

filtered_LLMs_temp = filtered_LLMs.copy()
filtered_LLMs_temp['key'] = 1

filtered_system_instructions_temp = filtered_system_instructions.copy()
filtered_system_instructions_temp['key'] = 1

filtered_developer_instructions_temp = filtered_developer_instructions.copy()
filtered_developer_instructions_temp['key'] = 1

filtered_phrase_template_temp = filtered_phrase_template.copy()
filtered_phrase_template_temp['key'] = 1

ReasoningLevel_temp = ReasoningLevel.copy()
ReasoningLevel_temp['key'] = 1

# Perform the merges (Cartesian product) starting with IcdConditions as the spine:
FPM_3 = pd.merge(IcdConditions_temp, filtered_LLMs_temp, on='key')
FPM_3 = pd.merge(FPM_3, filtered_system_instructions_temp, on='key')
FPM_3 = pd.merge(FPM_3, filtered_developer_instructions_temp, on='key')
FPM_3 = pd.merge(FPM_3, ReasoningLevel_temp, on='key') # Add ReasoningLevel here
FPM_3 = pd.merge(FPM_3, filtered_phrase_template_temp, on='key')

# Drop the dummy key column from the result:
FPM_3 = FPM_3.drop('key', axis=1)

# Sanity checks:
print("Head of FPM_3 DataFrame:")
print(FPM_3.head())
print(f"Shape of FPM_3: {FPM_3.shape}")

summary_table = FPM_3.groupby([
    'ModelName',
    'QueryPhraseContentLevelLabels',
    'DeveloperContentLevelLabels',
    'SystemContentLevelLabels',
    'ReasoningLevel' # Add ReasoningLevel here
]).size().reset_index(name='RecordCount')

print("\nSummary table of record counts:")
print(summary_table)

# Create final generated query through replacement of %X%:
FPM_3['GeneratedQueryContent'] = FPM_3.apply(
    lambda row: row['QueryPhraseContent'].replace('%X%', row['Title']), axis=1
)

print("Head of FPM_3 DataFrame with new 'GeneratedQueryContent' column:")
print(FPM_3[['Title', 'QueryPhraseContent', 'GeneratedQueryContent']].head())

"""## Run API fetcher to produce data"""

df = process_openai_queries(FPM_3)

# When finished:
FPM_3_Responses = df

# Save to csv:
FPM_3_Responses.to_csv('FPM_3_Responses.csv', index=False)

"""# Demo 4: Web search invocation as a function of reasoning effort, user persona, and query topic

## Create factorial prompt matrix
"""

# Filter the necessary DataFrames based on the specified conditions

filtered_system_instructions = ProductSystem_SystemInstructions[
    ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "None"
]

filtered_developer_instructions = ProductSystem_DeveloperInstructions[
    (ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "Persona: biomedical researcher") |
    (ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "None")
]
filtered_phrase_template = QueryDesign_QueryPhraseTemplate[
    (QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] == "General description") |
    (QueryDesign_QueryPhraseTemplate['QueryPhraseContentLevelLabels'] == "Risk factors")
]

# Filter LLMs to only include gpt-5.4-nano:
filtered_LLMs = LLMs[LLMs['ModelName'] == "gpt-5.4-nano"].copy()

# To create a Cartesian product, add a dummy key column to all DataFrames
IcdConditions_temp = IcdConditions.copy()
IcdConditions_temp['key'] = 1

filtered_LLMs_temp = filtered_LLMs.copy()
filtered_LLMs_temp['key'] = 1

filtered_system_instructions_temp = filtered_system_instructions.copy()
filtered_system_instructions_temp['key'] = 1

filtered_developer_instructions_temp = filtered_developer_instructions.copy()
filtered_developer_instructions_temp['key'] = 1

filtered_phrase_template_temp = filtered_phrase_template.copy()
filtered_phrase_template_temp['key'] = 1

ReasoningLevel_temp = ReasoningLevel.copy()
ReasoningLevel_temp['key'] = 1

# Perform the merges starting with IcdConditions as the spine
FPM_4 = pd.merge(IcdConditions_temp, filtered_LLMs_temp, on='key')
FPM_4 = pd.merge(FPM_4, filtered_system_instructions_temp, on='key')
FPM_4 = pd.merge(FPM_4, filtered_developer_instructions_temp, on='key')
FPM_4 = pd.merge(FPM_4, ReasoningLevel_temp, on='key')
FPM_4 = pd.merge(FPM_4, filtered_phrase_template_temp, on='key')

# Drop the dummy key column from the result
FPM_4 = FPM_4.drop('key', axis=1)

# Sanity checks:
print("Head of FPM_4 DataFrame:")
print(FPM_4.head())
print(f"Shape of FPM_4: {FPM_4.shape}")

summary_table = FPM_4.groupby([
    'ModelName',
    'QueryPhraseContentLevelLabels',
    'DeveloperContentLevelLabels',
    'ReasoningLevel'
]).size().reset_index(name='RecordCount')

print("\nSummary table of record counts:")
print(summary_table)

# Create final generated query:
FPM_4['GeneratedQueryContent'] = FPM_4.apply(
    lambda row: row['QueryPhraseContent'].replace('%X%', row['Title']), axis=1
)

print("Head of FPM_4 DataFrame with new 'GeneratedQueryContent' column:")
print(FPM_4[['Title', 'QueryPhraseContent', 'GeneratedQueryContent']].head())

"""## Run API fetcher to produce data"""

df = process_openai_queries(FPM_4)

# When finished:
FPM_4_Responses = df

# Save as csv:
FPM_4_Responses.to_csv('FPM_4_Responses.csv', index=False)

"""# Demo 5: Web search invocation and source localization as a function of query language, with repeated measures

## Create version of Icd Spine with 3 languages: English, Spanish, and Kazakh
"""

# Create language-specific phrase template:
QueryDesign_QueryPhraseTemplate_5 = pd.DataFrame(columns=['QueryPhraseContent', 'QueryPhraseContentLevelLabels'])

QueryPhraseContent = [
        "What is %X%?",
        "¿Qué es %X%?",
        "%X% дегеніміз не?"
    ]

QueryPhraseContentLevelLabels = [
        "General description",
        "General description",
        "General description"
    ]

QueryPhraseLanguage = [
     "English",
     "Spanish", # Added Spanish
     "Kazakh"
    ]

# Populate:
QueryDesign_QueryPhraseTemplate_5['QueryPhraseContent'] = QueryPhraseContent
QueryDesign_QueryPhraseTemplate_5['QueryPhraseContentLevelLabels'] = QueryPhraseContentLevelLabels
QueryDesign_QueryPhraseTemplate_5['QueryPhraseLanguage'] = QueryPhraseLanguage


# Display the dataframe to sanity-check:
print(QueryDesign_QueryPhraseTemplate_5)

# Note: translations provided by:
# World Health Organization. ICD-11: International Classification of Diseases,
#   Eleventh Revision [Internet]. Geneva: World Health Organization; 2019.
#   https://icd.who.int/browse11.

language_mapping_raw = """Title\tTitleKazakh\tTitleSpanish
Invasive aspergillosis of the digestive tract\tАсқорыту жүйесінің инвазиялық аспергиллезі\tla Aspergilosis invasora del tubo digestivo
Invasive cerebral aspergillosis\tИнвазиялық церебральды аспергиллез\tla Aspergilosis cerebral invasora
Disseminated aspergillosis\tДиссеминирленген аспергиллез\tla Aspergilosis diseminada
Aspergillus otomycosis\tАспергиллозды отомикоз\tla Otomicosis por Aspergillus
Chronic aspergillosis of the paranasal sinuses\tПараназальды синустардың созылмалы аспергиллезі\tla Aspergilosis crónica de los senos paranasales
Chronic pulmonary aspergillosis\tӨкпенің созылмалы аспергиллезі\tla Aspergilosis pulmonar crónica
Tonsillar aspergillosis\tТонзиллярлық аспергиллез\tla Aspergilosis amigdalina
Aspergillus bronchitis\tАспергилл бронхиті\tla Bronquitis por Aspergillus
Obstructing aspergillus tracheobronchitis\tАспергилльді трахеобронхитке кедергі жасау\tla Traqueobronquitis obstructiva por Aspergillus
Basidiobolomycosis\tБазидиоломикоз\tla Basidiobolomicosis
Blastomycosis\tБластомикоз\tla Blastomicosis
Candidosis of lips or oral mucous membranes\tЕріннің немесе ауыз қуысының шырышты қабығының кандидозы\tla Candidiasis labial o de la mucosa bucal
Vulvovaginal candidosis\tВульвовагинальды кандидоз\tla Candidiasis vulvovaginal
Candida balanoposthitis\tКандидозды баланопостит\tla Balanopostitis por Candida
Flexural or intertriginous candidosis\tКандидальды интертриго\tla Candidosis flexural o intertriginosa
Candidosis of nail or paronychium\tТырнақтардың немесе паронихияның кандидозы\tla Candidosis de la uña o el paroniquio
Chronic mucocutaneous candidosis\tШырышты қабықтың, терінің созылмалы кандидозы\tla Candidosis mucocutánea crónica
Disseminated cutaneous candidosis\tДиссеминирленген тері кандидозы\tla Candidosis cutánea diseminada
Candida otomycosis\tКандидозды отомикоз\tla Otomicosis por candida
Candidosis of gastrointestinal tract\tАсқазан-ішек жолдарының кандидозы\tla Candidiasis del sistema gastrointestinal
Candida meningitis\tКандидозды менингит\tla Meningitis por Candida
Pulmonary candidosis\tӨкпе кандидозы\tla Candidiasis pulmonar
Chromoblastomycosis\tХромобластомикоз\tla Cromoblastomicosis
Acute pulmonary coccidioidomycosis\tЖiтi өкпе кокцидиоидомикозы\tla Coccidioidomicosis pulmonar aguda
Chronic pulmonary coccidioidomycosis\tӨкпенің созылмалы кокцидиоидомикозы\tla Coccidioidomicosis pulmonar crónica
Disseminated coccidioidomycosis\tДиссеминирленген кокцидиоидомикоз\tla Coccidioidomicosis diseminada
Primary cutaneous coccidioidomycosis\tБіріншілік тері кокцидиомикозы\tla Coccidioidomicosis cutánea primaria
Coccidioides meningitis\tКокцидиоидты менингит\tla Meningitis coccidioides
Conidiobolomycosis\tКонидиоломикоз\tla Conidiobolomicosis
Pulmonary cryptococcosis\tӨкпенің криптококкозы\tla Criptococosis pulmonar
Disseminated cryptococcosis\tДиссеминирленген криптококкоз\tla Criptococosis diseminada
Dermatophytosis of scalp\tБас терісінің дерматофитозы\tla Dermatofitosis del cuero cabelludo
Dermatophytosis of nail\tТырнақ дерматофитозы\tla Dermatofitosis de las uñas
Dermatophytosis of foot\tАяқтардың дерматофитозы\tla Dermatofitosis del pie
Genitocrural dermatophytosis\tГенитокральды дерматофитоз\tla Dermatofitosis genitocrural
Kerion\tКерион\tel Querion
Disseminated dermatophytosis\tДиссеминирленген дерматофитоз\tla Dermatofitosis diseminada
Eumycetoma\tЭумицетома\tel Eumicetoma
Pulmonary histoplasmosis capsulati\tКапсулаланған өкпе гистоплазмозы\tla Histoplasmosis capsulati pulmonar
Histoplasmosis due to Histoplasma duboisii\tHistoplasma duboisii тудыратын гистоплазмоз\tla Histoplasmosis por Histoplasmosis duboisii
Lobomycosis\tЛобомикоз\tla Lobomicosis
Mucormycosis\tМукормикоз\tla Mucormicosis
Pityriasis versicolor\tПитриаз versicolor\tla Pitiriasis versicolor
Malassezia folliculitis\tМалассезия фолликулиті\tla Foliculitis por Malassezia
White piedra\tАқ пьедра\tla Piedra blanca
Black piedra\tҚара пьедра\tla Piedra negra
Tinea nigra\tҚара тін\tla Tiña negra
Onychomycosis due to non-dermatophyte mould\tДерматофитті емес зеңге байланысты онихомикоз\tla Onicomicosis por hongos no dermatofíticos
Pulmonary paracoccidioidomycosis\tӨкпенің паракокцидиоидомикозы\tla Paracoccidioidomicosis pulmonar
Disseminated paracoccidioidomycosis\tДиссеминирленген паракокцидиоидомикоз\tla Paracoccidioidomicosis diseminada
Phaeohyphomycosis\tФеогифомикоз\tla Feohifomicosis
Pulmonary pneumocystosis\tӨкпенің пневмоцистозы\tla Neumocistosis pulmonar
Scedosporiosis\tСкедоспориоз\tla Escedosporiosis
Lymphocutaneous sporotrichosis\tЛимфотері споротрихозы\tla Esporotricosis linfocutánea
Fixed cutaneous sporotrichosis\tФиксацияланған тері споротрикозы\tla Esporotricosis cutánea fija
Pulmonary sporotrichosis\tӨкпе споротрихозы\tla Esporotricosis pulmonar
Disseminated sporotrichosis\tДиссеминирленген споротрихоз\tla Esporotricosis diseminada
Talaromycosis\tТаларомикоз\tla Talaromicosis
Disseminated adiaspiromycosis\tДиссеминирленген адиаспиромикоз\tla Adiaspiromicosis diseminada
Pulmonary adiaspiromycosis\tӨкпе адиаспиромикозы\tla Adiaspiromicosis pulmonar
"""

LanguageMapping = pd.read_csv(StringIO(language_mapping_raw), sep="\t")

# Rename the original 'Title' column to 'EnglishTitle' and 'TitleKazakh' to 'KazakhTitle'
LanguageMapping = LanguageMapping.rename(columns={
    'Title': 'EnglishTitle',
    'TitleKazakh': 'KazakhTitle',
    'TitleSpanish': 'SpanishTitle' # Added for Spanish
})

LanguageMapping['Title'] = LanguageMapping['EnglishTitle']

# Reorder columns to "Title", "EnglishTitle", "KazakhTitle", "SpanishTitle"
IcdConditionsWithTranslations = LanguageMapping[['Title', 'EnglishTitle', 'KazakhTitle', 'SpanishTitle']]

print(IcdConditionsWithTranslations.head())
print(IcdConditionsWithTranslations.shape)

"""## Create factorial prompt matrix"""

# Filter as necessary for the factors used in demo 5:
filtered_system_instructions = ProductSystem_SystemInstructions[
    ProductSystem_SystemInstructions['SystemContentLevelLabels'] == "None"
]
filtered_developer_instructions = ProductSystem_DeveloperInstructions[
    ProductSystem_DeveloperInstructions['DeveloperContentLevelLabels'] == "None"
]
filtered_phrase_template = QueryDesign_QueryPhraseTemplate_5[
    QueryDesign_QueryPhraseTemplate_5['QueryPhraseContentLevelLabels'] == "General description"
]

# Filter LLMs to only include 'gpt-5-nano'
filtered_LLMs = LLMs[LLMs['ModelName'] == "gpt-5-nano"].copy()

# To create a Cartesian product, add a dummy key column to all dfs:
IcdConditions_temp = IcdConditionsWithTranslations.copy()
IcdConditions_temp['key'] = 1

filtered_LLMs_temp = filtered_LLMs.copy()
filtered_LLMs_temp['key'] = 1

filtered_system_instructions_temp = filtered_system_instructions.copy()
filtered_system_instructions_temp['key'] = 1

filtered_developer_instructions_temp = filtered_developer_instructions.copy()
filtered_developer_instructions_temp['key'] = 1

filtered_phrase_template_temp = filtered_phrase_template.copy()
filtered_phrase_template_temp['key'] = 1


# Perform the merges with IcdConditionsWithTranslations as the spine
FPM_5 = pd.merge(IcdConditions_temp, filtered_LLMs_temp, on='key')
FPM_5 = pd.merge(FPM_5, filtered_system_instructions_temp, on='key')
FPM_5 = pd.merge(FPM_5, filtered_developer_instructions_temp, on='key')
FPM_5 = pd.merge(FPM_5, filtered_phrase_template_temp, on='key')

# Drop the dummy key column from the result
FPM_5 = FPM_5.drop('key', axis=1)

# Sanity checks:
print("Head of FPM_5 DataFrame:")
print(FPM_5.head())
print(f"Shape of FPM_5: {FPM_5.shape}")

summary_table = FPM_5.groupby([
    'ModelName',
    'QueryPhraseLanguage'
]).size().reset_index(name='RecordCount')

print("\nSummary table of record counts:")
print(summary_table)

# Generate the final query content for each row. This involves replacing '%X%'
# in 'QueryPhraseContent' with the appropriate title based on the
# 'QueryPhraseLanguage'. For English queries, it uses 'EnglishTitle', for
# Spanish 'SpanishTitle', and for Kazakh 'KazakhTitle'.
FPM_5['GeneratedQueryContent'] = FPM_5.apply(
    lambda row:
        row['QueryPhraseContent'].replace(
            '%X%',
            row['EnglishTitle'] if row['QueryPhraseLanguage'] == 'English' else
            row['SpanishTitle'] if row['QueryPhraseLanguage'] == 'Spanish' else
            row['KazakhTitle'] # Default to KazakhTitle if not English or Spanish
        ),
    axis=1
)

print("Head of FPM_5 DataFrame with new 'GeneratedQueryContent' column:")
print(FPM_5[['Title', 'QueryPhraseLanguage', 'QueryPhraseContent', 'GeneratedQueryContent']].head())

# As this demo is a repeated measures design, create repetitions of each unique record in
# FPM_5 exactly 3 times and add a 'RepetitionIndex' to differentiate identical records.
FPM_5_repeated = pd.concat([FPM_5.assign(RepetitionIndex=i) for i in range(1, 4)], ignore_index=True);

# Update FPM_5 to the new df with repeated records
FPM_5 = FPM_5_repeated

print("Head of FPM_5 DataFrame with repeated records and RepetitionIndex:")
print(FPM_5[['Title', 'QueryPhraseLanguage', 'GeneratedQueryContent', 'RepetitionIndex']].head(9))
print(f"Shape of FPM_5: {FPM_5.shape})")

"""## Run API fetcher to produce data"""

df = process_openai_queries(FPM_5)

# When finished:
FPM_5_Responses = df

# Save as csv:
FPM_5_Responses.to_csv('FPM_5_Responses.csv', index=False)